tup=('a','b','c') 
print(tup)

list1 = [20,2.34,67]
print(list1)

print(len(list1))
print(max(list1))
print(sum(list1))
print(min(list1))
list1.sort()
print(list1)
list2=list(tup)
print(list2)
list1.append(20)
print(list1)
print(list1.count(20))
list1.extend([12,44,'hi'])
print(list1)
list1.extend(list2)
print(list1)
print(list1.pop())
print(list1.pop(7))
list1.remove(20)
print(list1)
list1.reverse()
print(list1)
list1.clear()
print(list1)


